name: 04 - Deploy Network Infrastructure

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Deployment environment"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod

      springProfile:
        description: "Active Spring Profile"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish backend
    outputs:
      imageTag: ${{ steps.imageTag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build backend application
        working-directory: backend
        run: ./mvnw -B package -DskipTests

      - name: Create Docker image tag
        id: imageTag
        run: |
          echo "tag=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
          | docker login --username AWS --password-stdin \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - name: Build and Push Docker image
        env:
          TAG: ${{ steps.imageTag.outputs.tag }}
        working-directory: backend
        run: |
          docker build -t finance-log .
          docker tag finance-log \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/finance-log:${TAG}
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/finance-log:${TAG}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy backend service
    needs: build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install CDK dependencies
        working-directory: infrastructure
        run: npm install

      - name: Deploy ECS Service
        working-directory: infrastructure
        run: |
          npm run service:deploy -- \
            -c environmentName=${{ github.event.inputs.environmentName }} \
            -c applicationName=finance-log \
            -c repositoryName=finance-log \
            -c imageTag=${{ needs.build-and-publish.outputs.imageTag }} \
            -c springProfile=${{ github.event.inputs.springProfile }}